apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-uwm
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-user-workload-monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: components/monitoring/prometheus
    repoURL: https://github.com/xcoulon/sandbox-sre-gitops.git
    targetRevision: HEAD
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    retry:
      limit: 50 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 15s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")