apiVersion: v1
kind: Secret
metadata:
  name: host-operator-secret
type: Opaque
stringData:
  mailgun.api.key: dummy-mailgun-api-key
  mailgun.domain: dummy.mailgun.cool.sandbox.domain.com
  mailgun.sender.email: noreply-dummy@cool.sandbox.domain.com
  mailgun.replyto.email: dummy-sandbox-list@cool.sandbox.domain.com
  twilio.account.sid: dummy-twilio-account-sid
  twilio.auth.token: dummy-twilio-auth-token
  twilio.from_number: +dummy-123456789

