apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: toolchain-host-operator

resources:
  - toolchain-host-operator.yaml
  - host-operator-secret.yaml
  - toolchain-config.yaml
