apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster-monitoring-configmap.yaml
- grafana-serviceaccount.yaml
- user-workload-monitoring-configmap.yaml

generatorOptions:
  disableNameSuffixHash: true
