apiVersion: v1
kind: Secret
metadata:
  name: member-operator-secret
  namespace: toolchain-member-operator
type: Opaque
stringData:
  che.admin.username: dummy-che-admin-username
  che.admin.password: dummy-che-admin-password

