apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- service-account.yaml
- deployment.yaml
- route.yaml
- service.yaml

namespace: "openshift-user-workload-monitoring"

generatorOptions:
  disableNameSuffixHash: true

# Grafana config maps
configMapGenerator:
- name: grafana-dashboard-definitions
  files:
  - example.json=dashboards/example.json

# Grafana secrets
secretGenerator:
- name: grafana-config
  files:
  - grafana.ini=grafana.ini