apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
---
# used by Grafana to connect to Prometheus via the OAuth Proxy (SA requires the "get ns" permission)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrole-cluster-monitoring-view-grafana
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
subjects:
- kind: ServiceAccount
  name: grafana
  # namespace is set/enforced by Kustomize