apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  namespace: openshift-logging
  name: cluster-logging
  labels:
    operators.coreos.com/cluster-logging.openshift-logging: ""
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cluster-logging
  source: redhat-operators
  sourceNamespace: openshift-marketplace
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  namespace: openshift-logging
  name: cluster-logging
spec:
  targetNamespaces:
  - openshift-logging