# see https://grafana.com/docs/loki/latest/configuration/
auth_enabled: false
chunk_store_config:
  max_look_back_period: 336h # same as limits_config.retention_period
ingester:
  chunk_block_size: 262144
  chunk_idle_period: 3m
  chunk_retain_period: 1m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  max_transfer_retries: 0
  wal:
    dir: "/data/wal"
limits_config:
  ingestion_burst_size_mb: 16
  retention_period: 336h
schema_config:
  configs:
  - from: "2020-10-15" # The date of the first day that index buckets should be created. Use a date in the past if this is your only period_config, otherwise use a date when you want the schema to switch over.
    index:
      period: 168h # 7 days
      prefix: index_
    schema: v11
    object_store: filesystem
    store: boltdb
  - from: "2023-01-12"
    index:
      period: 24h
      prefix: loki_index_
    object_store: filesystem
    schema: v11
    store: boltdb-shipper
server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 8388608
storage_config:
  boltdb: # legacy index
    directory: /data/loki/index
  boltdb_shipper:
    active_index_directory: /data/loki/index-boltdb-shipper
    cache_location: /data/loki/boltdb-shipper-cache
  filesystem:
    directory: /data/loki/chunks
compactor:
  working_directory: /data/loki/retention
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150