apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loki-thanos-querier
subjects:
- kind: ServiceAccount
  namespace: openshift-user-workload-monitoring
  name: loki
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: thanos-querier